### ISSUE TITLE
Bad names for commands

### ISSUE THREAD

**Issue by Untoldhacker-Dev** [Amith-Coder/CoinPayments#1]
![Screenshot_2021-11-23-19-53-18-999](https://user-images.githubusercontent.com/74806602/143041802-cf24b943-78cf-4dd3-b072-b120e1a5199c.jpeg)
Such command names are not good, users cannot understand it! Try to make combined commands, or compressed commands, like you can use params for sending amount to user: `/send [amount] [id]` .

**Comment by Amith-Coder** [comment]
Solved 
- I changed Command Name
