### ISSUE TITLE
Not good names yet shift to aliases

### ISSUE THREAD

**Issue by Untoldhacker-Dev** [Amith-Coder/CoinPayments#2]
![Screenshot_2021-11-24-12-54-58-439](https://user-images.githubusercontent.com/74806602/143193300-e191fabd-26d7-48f6-93f5-22411de83c20.jpeg)
You have command names like: 🤴 Referral 🤴
Please use Emoji-Text command names with aliases
## I.E: Please use Emoji-Text Command Names in aliases, and simple commands with '/' in command names. ##

**Comment by Amith-Coder** [comment]
Done solved
