### ISSUE TITLE
Bad code practice, Need to fix admin features

### ISSUE THREAD

**Issue by Untoldhacker-Dev** [Amith-Coder/CoinPayments#5]
You have such validation in commands:
![Screenshot_2021-11-24-13-06-41-785](https://user-images.githubusercontent.com/74806602/143194994-560a6cf9-4111-46b1-a825-c44c9aa3aa96.jpeg)

• Please use App-Admin Panel for this like:
![](https://user-images.githubusercontent.com/38240269/142182584-3e2b20e6-c5e6-482e-8893-f7650faf4080.png)

Also Please see - https://t.me/botsbus/1215
It is possible to check admin in before all command now!
So you don't need to check commands one by one

**Comment by Amith-Coder** [comment]
I tried the code which u given it have some problem I test it this so sorry
