### ISSUE TITLE
Not required ec validation

### ISSUE THREAD

**Issue by Untoldhacker-Dev** [Amith-Coder/CoinPayments#7]
Validation in every command is not required!
![Screenshot_2021-11-24-13-15-22-054](https://user-images.githubusercontent.com/74806602/143196098-c2a99da5-4689-401e-a005-162eb2f74ec0.jpeg)
Because you have: #5

**Comment by Amith-Coder** [comment]
Bro I was having problems in that so I do like this😅

**Comment by Amith-Coder** [comment]
Bro it have some problem
